name: Image Builder
on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: push-out

jobs:
  base:
    name: "Minetrack Image"
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '!norun') }}
    strategy:
      fail-fast: false
          
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: docker/setup-buildx-action@v2.2.1
        with:
          version: "v0.5.1"
          buildkitd-flags: --debug
      - uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      - uses: docker/build-push-action@v3.3.0
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
             ghcr.io/expxx/rapid:track
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
      - name: Restart Deployment
        run: kubectl rollout restart deployment minetrack --namespace=default
